spring.application.name=ecommerce
spring.profiles.default=dev
spring.jpa.open-in-view=false
spring.sql.init.mode=never
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=3MB
server.error.include-message=never
server.port=${PORT:8080}
app.jwt.secret=${JWT_SECRET:}
app.client-origin=${CLIENT_ORIGIN:http://localhost:4200}
app.bootstrap-admin.email=${APP_ADMIN_EMAIL:}
app.bootstrap-admin.password=${APP_ADMIN_PASSWORD:}
app.bootstrap-admin.name=${APP_ADMIN_NAME:Administrador}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
management.health.db.enabled=true
