spring.datasource.url=jdbc:sqlserver://localhost:63226;databaseName=ecommerceDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=ecommerce_user
spring.datasource.password=Pass123!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
app.client.url=http://localhost:4200/login
